### ISSUE TITLE
Feature Request: View complex np.ndarrays

### ISSUE THREAD

**Issue by Nin17** [elazarcoh/simply-view-image-for-python-debugging#18]
It'd be great if you could view the real and imaginary components of a complex np.ndarray separately.

**Comment by elazarcoh** [comment]
Would you like to provide me with a python code to do it? It would help me to create a release faster (otherwise, it's not in a priority for me, as I'm busy with other stuff)

I prefer to save it as a single image, maybe by concatenating the images (e.g. with `np.hstack`).
But if you prefer it as multiple separated images, then please make a function with this signature:
```python
from pathlib import Path

def preprocess_complex(img: np.ndarray, path: Path) -> Iterable[Tuple[np.ndarray, Path]]: 
    ...
```
