### ISSUE TITLE
No popup/response when debugging with an attach request to a remote machine.

### ISSUE THREAD

**Issue by b7leung** [elazarcoh/simply-view-image-for-python-debugging#36]
When I'm debugging with a launch request, eg with a configuration like 
```
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true
        },
```

the extension works great. However, when I'm debugging with an attach request, like
```
        {
            "name": "Attach name,
            "type": "python",
            "request": "attach",
            "host": "my_host_name",
            "port": host_port_num
        },
```
the "view image" hover popup does show, and variables are recorded in the "image watch" section, but when I click them nothing happens (there is no side window showing the image).
It would be amazing if this extension could be used for attach debugging sessions, which is how I always debug in my use case; I cannot debug through a launch config.

**Comment by elazarcoh** [comment]
I'll look into it

**Comment by elazarcoh** [comment]
Okay, seems since the debug is performed remotely, and the extension is running locally, the save paths are local paths.
For a debug inside local docker container, a workaround might be to map local paths into remote paths. This might not work very easily, though. Maybe only if both remote and local platforms are the same (e.g. linux-linux). 

(Note to myself) A possible solution is to pass the entire image as bytes via the debugger, and save it locally. This needed only for such cases where the debugger and VSCode do not share the same filesystem. Need to find a way to figure out how can I detect that from `vscode.debug.activeDebugSession` (maybe in `vscode.debug.activeDebugSession.debugOptions`)

**Comment by b7leung** [comment]
Actually, it seems like just unchecking ustetmppathtosave fixed the issue. Like you mentioned, the issue was not being able to find paths. Thankfully, my case is a bit simpler, and my local and remote share the same home directory (accessing the same storage), but are different machines (so have a different /tmp folder).

**Comment by elazarcoh** [comment]
Great to hear that was simple enough for your case!

I'll keep this issue open and will get around  fixing it in a more complete way when I have the time for it.

**Comment by MaKaNu** [comment]
I have probably a similar issue (can't find outputs from the extension) but instead of a local docker I am connected to a remote ssh server. unchecking usetmppathtosave was not successful for me, since remote linux and local windows. Any workarround for this situation?
